### ISSUE TITLE
Composer // Выяснить нужно ли нам для разработки minimum-stability

### ISSUE THREAD

**Issue by antode** [15web/sailplay-php#1]
minimum-stability и prefer-stable это [root-only](https://getcomposer.org/doc/04-schema.md#root-package) директивы

root-only - не учитывается если наш пакет подключается как вендорский. Будет работать только если клонировать сам репозиторий пакета. То есть директива имеет смысл только для разработки

нужно выяснить потребуются ли они при разработке для обновления завсимостей

- нужно понять будут ли влиять эти директивы при обновлении пакетов на их версии
- придумать как это проверить
- описать результаты

**Comment by rleekg** [comment]
[minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) может быть: `dev`, `alpha`, `beta`, `RC`, and `stable`

Если minimum-stability равен `stable` то, устанавливаются только стабильные версии. В этом случае мы не сможем поставить пакеты не стабильной версии: `dev-master`, `@dev`.  Будет ошибка вида:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires package/name-stable ^0.0.5 -> satisfiable by  package/name-stable[v0.0.5].
    -  package/name-stable v0.0.5 requires package/name-dev 2.* -> could not be found in any version, there may be a typo in the package name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require  package/name-stable:*" to figure out if any version is installable, or "composer require  package/name-dev:^2.1" if you know which you need.
```
Тут мы устанавливаем стабильный пакет у которого в зависимости требуется не стабильная версия.

Что можно сделать:
- Установить minimum-stability в dev в корневом composer.json файле. В этом случае также следует добавить "prefer-stable": true, чтобы по возможности ставились стабильные пакеты.
- Использовать [stability flags](https://getcomposer.org/doc/04-schema.md#package-links), явно указав флаг в корневом пакете: "package/name-dev": "@dev".

Лучше minimum-stability оставить по умолчанию как есть `stable`, а если нужны будут пакеты у которых в зависимостях есть не стабильные пакеты, добавлять их явно в корневой проект с флагом `@dev`, `@RC`, `@beta` 

Ссылка [ссылку](https://igor.io/2013/02/07/composer-stability-flags.html) на статью с подробным объяснением minimum-stability.

**Comment by antode** [comment]
Отлично!
Оставляем конфиг как есть.
