### ISSUE TITLE
Реализовать метод // users/add

### ISSUE THREAD

**Issue by antode** [15web/sailplay-php#13]
https://ru.sailplay.dev/reference/users-add

Протестировать 
- [users/add](https://ru.sailplay.dev/reference/users-add)
- [users/info](https://ru.sailplay.dev/reference/users-info)
- посмотреть в личном кабинете тестового аккаунта

**Comment by rleekg** [comment]
Ссылка на PR: https://github.com/15web/sailplay-php/pull/19
