### ISSUE TITLE
Реализовать метод // purchases/purchase-attributes/add

### ISSUE THREAD

**Issue by antode** [15web/sailplay-php#18]
https://ru.sailplay.dev/reference/purchases-purchase-attributes-add

Проверить атрибут в личном кабинете.

Проверить [создание покупки](https://ru.sailplay.dev/reference/purchases-new) с этим атрибутом. Проверить в личном кабинете.

**Comment by AntonZemlya** [comment]
> Проверить атрибут в личном кабинете.

Проверил, работает

> Проверить [создание покупки](https://ru.sailplay.dev/reference/purchases-new) с этим атрибутом.

Не могу, создание покупки не готово, только если через личный кабинет делать.

**Comment by antode** [comment]
> Проверил, работает
а где там это можно посмотреть?

> Не могу, создание покупки не готово, только если через личный кабинет делать.
через личный кабинет или руками из интерфейса документации, или всё вместе

**Comment by AntonZemlya** [comment]
> а где там это можно посмотреть?

Можно проверить через документацию, получить список всех атрибутов: https://ru.sailplay.dev/reference/purchases-purchase-attributes-list

**Comment by AntonZemlya** [comment]
Попробовал создать покупку с созланным атрибутом через интерфейс документации, получил невразумительную ошибку, что параметр "force_complete
boolean" должен быть 1 или 0. Т.е. их родной интерфейс не работает с ошибками.

Через ЛК получилось создать: https://sailplay.ru/spanel/v2/#/purchases/list?filtersModel=%255B%257B%257D%255D&purchaseId=670086022 (в правой колонке показан атрибут)

**Comment by antode** [comment]
> Попробовал создать покупку с созданным атрибутом через интерфейс документации, получил ошибку, что параметр "force_complete" (boolean) должен быть 1 или 0, а выбрать можно true/false.
> 
> Через ЛК получилось создать покупку (в правой колонке показан атрибут): https://sailplay.ru/spanel/v2/#/purchases/list?filtersModel=%255B%257B%257D%255D&purchaseId=670086022
