### ISSUE TITLE
Guzzle // Выяснить причину проблем с сертификатами

### ISSUE THREAD

**Issue by antode** [15web/sailplay-php#2]
При попытке выполнить запрос:
```console
./bin/run.bash php tests/functional/api_request.php
```
приложение падает с ошибкой
```
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://sailplay.ru/api/v2/login/ in /home/dev/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
Stack trace:
#0 /home/dev/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/dev/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/dev/app/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/dev/app/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\ in /home/dev/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 211
```

для проверки сделал
```php
new GuzzleHttp\Client(['verify' => false]),
```

и заработало

поверхностно погуглил:
- https://docs.guzzlephp.org/en/stable/request-options.html#verify-option
- https://github.com/guzzle/guzzle/issues/1935
- https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate

Что нужно делать:
- Разобраться, в сути проблемы, описать.
- Проверить есть ли она локально или это происходит только в докере.
- Подумать над вариантами решения, описать.

**Comment by rleekg** [comment]
> * Разобраться, в сути проблемы, описать.

Суть проблемы, в образе докера `php:7.2.5-cli`, по всей видимости старый образ который давно не обновлялся
https://hub.docker.com/layers/php/library/php/7.2.5-cli/images/sha256-c6c84906a3a028c66c699643736e13d3b60566d191688188e22ac2d472c3baa0?context=explore

Устарели cacerts ОС. Подробности [здесь](https://stackoverflow.com/questions/69413090/old-php-container-says-curl-60-ssl-certificate-problem-certificate-has-exp)
> * Проверить есть ли она локально или это происходит только в докере.

Локально нет ошибки, в докере есть.

> * Подумать над вариантами решения, описать.
* Увеличение версии PHP до 7.2.20 (начиная с 7.2.20 ошибки нет)
* Установить сертификат в ручную 
  * Загрузить https://curl.se/ca/cacert.pem
  * Установить параметр в php.ini: `curl.cainfo=путь до файла cacert.pem`
*  Установить сертификат https://curl.se/ca/cacert.pem в докере
Варианты расписаны [здесь](https://stackoverflow.com/questions/69413090/old-php-container-says-curl-60-ssl-certificate-problem-certificate-has-exp)

**Comment by antode** [comment]
понравилось решение [отсюда](https://stackoverflow.com/questions/69413090/old-php-container-says-curl-60-ssl-certificate-problem-certificate-has-exp/69413091#69413091)
```
apt-get update
apt-get upgrade -y
```

сделал коммит в main https://github.com/15web/sailplay-php/commit/f60672aa3521c14476231856a2cfd6832c6f6864
